{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "55fa34c4",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "from stable_baselines3 import PPO\n",
    "from src.data_processor import add_technical_indicators, extract_regimes\n",
    "from src.environment import OptimalExecutionEnv"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "f965ce8d",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Model is not converging.  Current: 578633.4478221749 is not greater than 578641.9232816672. Delta is -8.475459492299706\n"
     ]
    }
   ],
   "source": [
    "df_raw = pd.read_csv(\"data/BTCUSDT_1h_FINAL.csv\")\n",
    "df_enriched = add_technical_indicators(df_raw)\n",
    "df_final, transmat = extract_regimes(df_enriched)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "709c4f67",
   "metadata": {},
   "outputs": [],
   "source": [
    "train_df = df_final[df_final['Open_Time'] < '2024-01-01']\n",
    "test_df = df_final[df_final['Open_Time'] >= '2024-01-01']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "32ef3955",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Using cpu device\n",
      "Wrapping the env with a `Monitor` wrapper\n",
      "Wrapping the env in a DummyVecEnv.\n",
      "Entraînement en cours\n",
      "---------------------------------\n",
      "| rollout/           |          |\n",
      "|    ep_len_mean     | 5.55     |\n",
      "|    ep_rew_mean     | 238      |\n",
      "| time/              |          |\n",
      "|    fps             | 799      |\n",
      "|    iterations      | 1        |\n",
      "|    time_elapsed    | 2        |\n",
      "|    total_timesteps | 2048     |\n",
      "---------------------------------\n",
      "------------------------------------------\n",
      "| rollout/                |              |\n",
      "|    ep_len_mean          | 6.87         |\n",
      "|    ep_rew_mean          | 231          |\n",
      "| time/                   |              |\n",
      "|    fps                  | 331          |\n",
      "|    iterations           | 2            |\n",
      "|    time_elapsed         | 12           |\n",
      "|    total_timesteps      | 4096         |\n",
      "| train/                  |              |\n",
      "|    approx_kl            | 0.0023849763 |\n",
      "|    clip_fraction        | 0.0083       |\n",
      "|    clip_range           | 0.2          |\n",
      "|    entropy_loss         | -1.42        |\n",
      "|    explained_variance   | -0.00147     |\n",
      "|    learning_rate        | 0.0003       |\n",
      "|    loss                 | 1.13e+04     |\n",
      "|    n_updates            | 10           |\n",
      "|    policy_gradient_loss | -0.00153     |\n",
      "|    std                  | 1.01         |\n",
      "|    value_loss           | 3.09e+04     |\n",
      "------------------------------------------\n",
      "------------------------------------------\n",
      "| rollout/                |              |\n",
      "|    ep_len_mean          | 5            |\n",
      "|    ep_rew_mean          | 221          |\n",
      "| time/                   |              |\n",
      "|    fps                  | 302          |\n",
      "|    iterations           | 3            |\n",
      "|    time_elapsed         | 20           |\n",
      "|    total_timesteps      | 6144         |\n",
      "| train/                  |              |\n",
      "|    approx_kl            | 0.0039725425 |\n",
      "|    clip_fraction        | 0.00469      |\n",
      "|    clip_range           | 0.2          |\n",
      "|    entropy_loss         | -1.43        |\n",
      "|    explained_variance   | 0.00299      |\n",
      "|    learning_rate        | 0.0003       |\n",
      "|    loss                 | 1.53e+04     |\n",
      "|    n_updates            | 20           |\n",
      "|    policy_gradient_loss | -0.000393    |\n",
      "|    std                  | 1.02         |\n",
      "|    value_loss           | 2.92e+04     |\n",
      "------------------------------------------\n",
      "------------------------------------------\n",
      "| rollout/                |              |\n",
      "|    ep_len_mean          | 5.18         |\n",
      "|    ep_rew_mean          | 245          |\n",
      "| time/                   |              |\n",
      "|    fps                  | 297          |\n",
      "|    iterations           | 4            |\n",
      "|    time_elapsed         | 27           |\n",
      "|    total_timesteps      | 8192         |\n",
      "| train/                  |              |\n",
      "|    approx_kl            | 0.0056284443 |\n",
      "|    clip_fraction        | 0.0233       |\n",
      "|    clip_range           | 0.2          |\n",
      "|    entropy_loss         | -1.43        |\n",
      "|    explained_variance   | 0.000622     |\n",
      "|    learning_rate        | 0.0003       |\n",
      "|    loss                 | 1.1e+04      |\n",
      "|    n_updates            | 30           |\n",
      "|    policy_gradient_loss | -0.0038      |\n",
      "|    std                  | 1.01         |\n",
      "|    value_loss           | 2.55e+04     |\n",
      "------------------------------------------\n",
      "------------------------------------------\n",
      "| rollout/                |              |\n",
      "|    ep_len_mean          | 4.6          |\n",
      "|    ep_rew_mean          | 239          |\n",
      "| time/                   |              |\n",
      "|    fps                  | 294          |\n",
      "|    iterations           | 5            |\n",
      "|    time_elapsed         | 34           |\n",
      "|    total_timesteps      | 10240        |\n",
      "| train/                  |              |\n",
      "|    approx_kl            | 0.0018448987 |\n",
      "|    clip_fraction        | 0.00728      |\n",
      "|    clip_range           | 0.2          |\n",
      "|    entropy_loss         | -1.42        |\n",
      "|    explained_variance   | 0.000292     |\n",
      "|    learning_rate        | 0.0003       |\n",
      "|    loss                 | 2.36e+04     |\n",
      "|    n_updates            | 40           |\n",
      "|    policy_gradient_loss | -0.000789    |\n",
      "|    std                  | 0.998        |\n",
      "|    value_loss           | 2.86e+04     |\n",
      "------------------------------------------\n",
      "------------------------------------------\n",
      "| rollout/                |              |\n",
      "|    ep_len_mean          | 6.12         |\n",
      "|    ep_rew_mean          | 258          |\n",
      "| time/                   |              |\n",
      "|    fps                  | 289          |\n",
      "|    iterations           | 6            |\n",
      "|    time_elapsed         | 42           |\n",
      "|    total_timesteps      | 12288        |\n",
      "| train/                  |              |\n",
      "|    approx_kl            | 0.0029218511 |\n",
      "|    clip_fraction        | 0.0275       |\n",
      "|    clip_range           | 0.2          |\n",
      "|    entropy_loss         | -1.42        |\n",
      "|    explained_variance   | 0.000144     |\n",
      "|    learning_rate        | 0.0003       |\n",
      "|    loss                 | 1.48e+04     |\n",
      "|    n_updates            | 50           |\n",
      "|    policy_gradient_loss | -0.0036      |\n",
      "|    std                  | 0.994        |\n",
      "|    value_loss           | 2.71e+04     |\n",
      "------------------------------------------\n",
      "------------------------------------------\n",
      "| rollout/                |              |\n",
      "|    ep_len_mean          | 3.95         |\n",
      "|    ep_rew_mean          | 243          |\n",
      "| time/                   |              |\n",
      "|    fps                  | 286          |\n",
      "|    iterations           | 7            |\n",
      "|    time_elapsed         | 50           |\n",
      "|    total_timesteps      | 14336        |\n",
      "| train/                  |              |\n",
      "|    approx_kl            | 0.0031067575 |\n",
      "|    clip_fraction        | 0.0484       |\n",
      "|    clip_range           | 0.2          |\n",
      "|    entropy_loss         | -1.41        |\n",
      "|    explained_variance   | 9.85e-05     |\n",
      "|    learning_rate        | 0.0003       |\n",
      "|    loss                 | 1.74e+04     |\n",
      "|    n_updates            | 60           |\n",
      "|    policy_gradient_loss | -0.00372     |\n",
      "|    std                  | 0.985        |\n",
      "|    value_loss           | 2.5e+04      |\n",
      "------------------------------------------\n",
      "------------------------------------------\n",
      "| rollout/                |              |\n",
      "|    ep_len_mean          | 4.56         |\n",
      "|    ep_rew_mean          | 272          |\n",
      "| time/                   |              |\n",
      "|    fps                  | 281          |\n",
      "|    iterations           | 8            |\n",
      "|    time_elapsed         | 58           |\n",
      "|    total_timesteps      | 16384        |\n",
      "| train/                  |              |\n",
      "|    approx_kl            | 0.0032166094 |\n",
      "|    clip_fraction        | 0.0191       |\n",
      "|    clip_range           | 0.2          |\n",
      "|    entropy_loss         | -1.39        |\n",
      "|    explained_variance   | 6.38e-05     |\n",
      "|    learning_rate        | 0.0003       |\n",
      "|    loss                 | 1.18e+04     |\n",
      "|    n_updates            | 70           |\n",
      "|    policy_gradient_loss | -0.00142     |\n",
      "|    std                  | 0.968        |\n",
      "|    value_loss           | 2.64e+04     |\n",
      "------------------------------------------\n",
      "------------------------------------------\n",
      "| rollout/                |              |\n",
      "|    ep_len_mean          | 3.57         |\n",
      "|    ep_rew_mean          | 233          |\n",
      "| time/                   |              |\n",
      "|    fps                  | 281          |\n",
      "|    iterations           | 9            |\n",
      "|    time_elapsed         | 65           |\n",
      "|    total_timesteps      | 18432        |\n",
      "| train/                  |              |\n",
      "|    approx_kl            | 0.0026870077 |\n",
      "|    clip_fraction        | 0.0356       |\n",
      "|    clip_range           | 0.2          |\n",
      "|    entropy_loss         | -1.37        |\n",
      "|    explained_variance   | 5.69e-05     |\n",
      "|    learning_rate        | 0.0003       |\n",
      "|    loss                 | 1.89e+04     |\n",
      "|    n_updates            | 80           |\n",
      "|    policy_gradient_loss | -0.00191     |\n",
      "|    std                  | 0.949        |\n",
      "|    value_loss           | 2.47e+04     |\n",
      "------------------------------------------\n",
      "------------------------------------------\n",
      "| rollout/                |              |\n",
      "|    ep_len_mean          | 3.26         |\n",
      "|    ep_rew_mean          | 221          |\n",
      "| time/                   |              |\n",
      "|    fps                  | 282          |\n",
      "|    iterations           | 10           |\n",
      "|    time_elapsed         | 72           |\n",
      "|    total_timesteps      | 20480        |\n",
      "| train/                  |              |\n",
      "|    approx_kl            | 0.0023992923 |\n",
      "|    clip_fraction        | 0.0221       |\n",
      "|    clip_range           | 0.2          |\n",
      "|    entropy_loss         | -1.36        |\n",
      "|    explained_variance   | 4.04e-05     |\n",
      "|    learning_rate        | 0.0003       |\n",
      "|    loss                 | 1.28e+04     |\n",
      "|    n_updates            | 90           |\n",
      "|    policy_gradient_loss | -0.00129     |\n",
      "|    std                  | 0.933        |\n",
      "|    value_loss           | 2.29e+04     |\n",
      "------------------------------------------\n",
      "------------------------------------------\n",
      "| rollout/                |              |\n",
      "|    ep_len_mean          | 4.11         |\n",
      "|    ep_rew_mean          | 235          |\n",
      "| time/                   |              |\n",
      "|    fps                  | 285          |\n",
      "|    iterations           | 11           |\n",
      "|    time_elapsed         | 78           |\n",
      "|    total_timesteps      | 22528        |\n",
      "| train/                  |              |\n",
      "|    approx_kl            | 0.0035095178 |\n",
      "|    clip_fraction        | 0.0216       |\n",
      "|    clip_range           | 0.2          |\n",
      "|    entropy_loss         | -1.35        |\n",
      "|    explained_variance   | 3.21e-05     |\n",
      "|    learning_rate        | 0.0003       |\n",
      "|    loss                 | 8.88e+03     |\n",
      "|    n_updates            | 100          |\n",
      "|    policy_gradient_loss | -0.000623    |\n",
      "|    std                  | 0.93         |\n",
      "|    value_loss           | 2.67e+04     |\n",
      "------------------------------------------\n",
      "-----------------------------------------\n",
      "| rollout/                |             |\n",
      "|    ep_len_mean          | 4.11        |\n",
      "|    ep_rew_mean          | 232         |\n",
      "| time/                   |             |\n",
      "|    fps                  | 291         |\n",
      "|    iterations           | 12          |\n",
      "|    time_elapsed         | 84          |\n",
      "|    total_timesteps      | 24576       |\n",
      "| train/                  |             |\n",
      "|    approx_kl            | 0.002054662 |\n",
      "|    clip_fraction        | 0.0187      |\n",
      "|    clip_range           | 0.2         |\n",
      "|    entropy_loss         | -1.34       |\n",
      "|    explained_variance   | 3.77e-05    |\n",
      "|    learning_rate        | 0.0003      |\n",
      "|    loss                 | 1.01e+04    |\n",
      "|    n_updates            | 110         |\n",
      "|    policy_gradient_loss | -0.00152    |\n",
      "|    std                  | 0.92        |\n",
      "|    value_loss           | 2.39e+04    |\n",
      "-----------------------------------------\n",
      "-----------------------------------------\n",
      "| rollout/                |             |\n",
      "|    ep_len_mean          | 3.59        |\n",
      "|    ep_rew_mean          | 248         |\n",
      "| time/                   |             |\n",
      "|    fps                  | 295         |\n",
      "|    iterations           | 13          |\n",
      "|    time_elapsed         | 90          |\n",
      "|    total_timesteps      | 26624       |\n",
      "| train/                  |             |\n",
      "|    approx_kl            | 0.005206589 |\n",
      "|    clip_fraction        | 0.0331      |\n",
      "|    clip_range           | 0.2         |\n",
      "|    entropy_loss         | -1.33       |\n",
      "|    explained_variance   | 0.00148     |\n",
      "|    learning_rate        | 0.0003      |\n",
      "|    loss                 | 6.82e+03    |\n",
      "|    n_updates            | 120         |\n",
      "|    policy_gradient_loss | -0.00174    |\n",
      "|    std                  | 0.911       |\n",
      "|    value_loss           | 2e+04       |\n",
      "-----------------------------------------\n",
      "-------------------------------------------\n",
      "| rollout/                |               |\n",
      "|    ep_len_mean          | 4.04          |\n",
      "|    ep_rew_mean          | 239           |\n",
      "| time/                   |               |\n",
      "|    fps                  | 292           |\n",
      "|    iterations           | 14            |\n",
      "|    time_elapsed         | 98            |\n",
      "|    total_timesteps      | 28672         |\n",
      "| train/                  |               |\n",
      "|    approx_kl            | 0.00075800245 |\n",
      "|    clip_fraction        | 0             |\n",
      "|    clip_range           | 0.2           |\n",
      "|    entropy_loss         | -1.32         |\n",
      "|    explained_variance   | 0.00842       |\n",
      "|    learning_rate        | 0.0003        |\n",
      "|    loss                 | 8.27e+03      |\n",
      "|    n_updates            | 130           |\n",
      "|    policy_gradient_loss | -0.000718     |\n",
      "|    std                  | 0.906         |\n",
      "|    value_loss           | 2.36e+04      |\n",
      "-------------------------------------------\n",
      "-------------------------------------------\n",
      "| rollout/                |               |\n",
      "|    ep_len_mean          | 4.2           |\n",
      "|    ep_rew_mean          | 230           |\n",
      "| time/                   |               |\n",
      "|    fps                  | 291           |\n",
      "|    iterations           | 15            |\n",
      "|    time_elapsed         | 105           |\n",
      "|    total_timesteps      | 30720         |\n",
      "| train/                  |               |\n",
      "|    approx_kl            | 0.00022599075 |\n",
      "|    clip_fraction        | 0             |\n",
      "|    clip_range           | 0.2           |\n",
      "|    entropy_loss         | -1.32         |\n",
      "|    explained_variance   | 0.124         |\n",
      "|    learning_rate        | 0.0003        |\n",
      "|    loss                 | 7.31e+03      |\n",
      "|    n_updates            | 140           |\n",
      "|    policy_gradient_loss | -0.000333     |\n",
      "|    std                  | 0.906         |\n",
      "|    value_loss           | 2.04e+04      |\n",
      "-------------------------------------------\n",
      "-----------------------------------------\n",
      "| rollout/                |             |\n",
      "|    ep_len_mean          | 3.65        |\n",
      "|    ep_rew_mean          | 234         |\n",
      "| time/                   |             |\n",
      "|    fps                  | 289         |\n",
      "|    iterations           | 16          |\n",
      "|    time_elapsed         | 113         |\n",
      "|    total_timesteps      | 32768       |\n",
      "| train/                  |             |\n",
      "|    approx_kl            | 0.002532049 |\n",
      "|    clip_fraction        | 0.00122     |\n",
      "|    clip_range           | 0.2         |\n",
      "|    entropy_loss         | -1.32       |\n",
      "|    explained_variance   | 0.201       |\n",
      "|    learning_rate        | 0.0003      |\n",
      "|    loss                 | 1.16e+04    |\n",
      "|    n_updates            | 150         |\n",
      "|    policy_gradient_loss | -0.000977   |\n",
      "|    std                  | 0.905       |\n",
      "|    value_loss           | 2.12e+04    |\n",
      "-----------------------------------------\n",
      "------------------------------------------\n",
      "| rollout/                |              |\n",
      "|    ep_len_mean          | 3.34         |\n",
      "|    ep_rew_mean          | 268          |\n",
      "| time/                   |              |\n",
      "|    fps                  | 286          |\n",
      "|    iterations           | 17           |\n",
      "|    time_elapsed         | 121          |\n",
      "|    total_timesteps      | 34816        |\n",
      "| train/                  |              |\n",
      "|    approx_kl            | 0.0029195508 |\n",
      "|    clip_fraction        | 0.00459      |\n",
      "|    clip_range           | 0.2          |\n",
      "|    entropy_loss         | -1.32        |\n",
      "|    explained_variance   | 0.213        |\n",
      "|    learning_rate        | 0.0003       |\n",
      "|    loss                 | 1.24e+04     |\n",
      "|    n_updates            | 160          |\n",
      "|    policy_gradient_loss | -0.00118     |\n",
      "|    std                  | 0.904        |\n",
      "|    value_loss           | 2.22e+04     |\n",
      "------------------------------------------\n",
      "-------------------------------------------\n",
      "| rollout/                |               |\n",
      "|    ep_len_mean          | 3.93          |\n",
      "|    ep_rew_mean          | 241           |\n",
      "| time/                   |               |\n",
      "|    fps                  | 289           |\n",
      "|    iterations           | 18            |\n",
      "|    time_elapsed         | 127           |\n",
      "|    total_timesteps      | 36864         |\n",
      "| train/                  |               |\n",
      "|    approx_kl            | 0.00024593482 |\n",
      "|    clip_fraction        | 0             |\n",
      "|    clip_range           | 0.2           |\n",
      "|    entropy_loss         | -1.32         |\n",
      "|    explained_variance   | 0.221         |\n",
      "|    learning_rate        | 0.0003        |\n",
      "|    loss                 | 2.02e+04      |\n",
      "|    n_updates            | 170           |\n",
      "|    policy_gradient_loss | -0.00016      |\n",
      "|    std                  | 0.904         |\n",
      "|    value_loss           | 2.5e+04       |\n",
      "-------------------------------------------\n",
      "------------------------------------------\n",
      "| rollout/                |              |\n",
      "|    ep_len_mean          | 4.12         |\n",
      "|    ep_rew_mean          | 250          |\n",
      "| time/                   |              |\n",
      "|    fps                  | 289          |\n",
      "|    iterations           | 19           |\n",
      "|    time_elapsed         | 134          |\n",
      "|    total_timesteps      | 38912        |\n",
      "| train/                  |              |\n",
      "|    approx_kl            | 0.0013458751 |\n",
      "|    clip_fraction        | 0.00264      |\n",
      "|    clip_range           | 0.2          |\n",
      "|    entropy_loss         | -1.32        |\n",
      "|    explained_variance   | 0.27         |\n",
      "|    learning_rate        | 0.0003       |\n",
      "|    loss                 | 1.45e+04     |\n",
      "|    n_updates            | 180          |\n",
      "|    policy_gradient_loss | 0.000148     |\n",
      "|    std                  | 0.904        |\n",
      "|    value_loss           | 2e+04        |\n",
      "------------------------------------------\n",
      "------------------------------------------\n",
      "| rollout/                |              |\n",
      "|    ep_len_mean          | 3.69         |\n",
      "|    ep_rew_mean          | 244          |\n",
      "| time/                   |              |\n",
      "|    fps                  | 290          |\n",
      "|    iterations           | 20           |\n",
      "|    time_elapsed         | 140          |\n",
      "|    total_timesteps      | 40960        |\n",
      "| train/                  |              |\n",
      "|    approx_kl            | 0.0021521999 |\n",
      "|    clip_fraction        | 0.0146       |\n",
      "|    clip_range           | 0.2          |\n",
      "|    entropy_loss         | -1.32        |\n",
      "|    explained_variance   | 0.285        |\n",
      "|    learning_rate        | 0.0003       |\n",
      "|    loss                 | 8.03e+03     |\n",
      "|    n_updates            | 190          |\n",
      "|    policy_gradient_loss | -0.00197     |\n",
      "|    std                  | 0.905        |\n",
      "|    value_loss           | 1.93e+04     |\n",
      "------------------------------------------\n",
      "-----------------------------------------\n",
      "| rollout/                |             |\n",
      "|    ep_len_mean          | 3.73        |\n",
      "|    ep_rew_mean          | 225         |\n",
      "| time/                   |             |\n",
      "|    fps                  | 292         |\n",
      "|    iterations           | 21          |\n",
      "|    time_elapsed         | 146         |\n",
      "|    total_timesteps      | 43008       |\n",
      "| train/                  |             |\n",
      "|    approx_kl            | 0.002744243 |\n",
      "|    clip_fraction        | 0.00908     |\n",
      "|    clip_range           | 0.2         |\n",
      "|    entropy_loss         | -1.32       |\n",
      "|    explained_variance   | 0.241       |\n",
      "|    learning_rate        | 0.0003      |\n",
      "|    loss                 | 1.25e+04    |\n",
      "|    n_updates            | 200         |\n",
      "|    policy_gradient_loss | -0.00193    |\n",
      "|    std                  | 0.905       |\n",
      "|    value_loss           | 2.16e+04    |\n",
      "-----------------------------------------\n",
      "------------------------------------------\n",
      "| rollout/                |              |\n",
      "|    ep_len_mean          | 3.6          |\n",
      "|    ep_rew_mean          | 241          |\n",
      "| time/                   |              |\n",
      "|    fps                  | 294          |\n",
      "|    iterations           | 22           |\n",
      "|    time_elapsed         | 153          |\n",
      "|    total_timesteps      | 45056        |\n",
      "| train/                  |              |\n",
      "|    approx_kl            | 0.0028827505 |\n",
      "|    clip_fraction        | 0.0154       |\n",
      "|    clip_range           | 0.2          |\n",
      "|    entropy_loss         | -1.32        |\n",
      "|    explained_variance   | 0.301        |\n",
      "|    learning_rate        | 0.0003       |\n",
      "|    loss                 | 8.3e+03      |\n",
      "|    n_updates            | 210          |\n",
      "|    policy_gradient_loss | -0.00164     |\n",
      "|    std                  | 0.898        |\n",
      "|    value_loss           | 1.53e+04     |\n",
      "------------------------------------------\n",
      "------------------------------------------\n",
      "| rollout/                |              |\n",
      "|    ep_len_mean          | 3.53         |\n",
      "|    ep_rew_mean          | 287          |\n",
      "| time/                   |              |\n",
      "|    fps                  | 295          |\n",
      "|    iterations           | 23           |\n",
      "|    time_elapsed         | 159          |\n",
      "|    total_timesteps      | 47104        |\n",
      "| train/                  |              |\n",
      "|    approx_kl            | 0.0014050454 |\n",
      "|    clip_fraction        | 0.0124       |\n",
      "|    clip_range           | 0.2          |\n",
      "|    entropy_loss         | -1.31        |\n",
      "|    explained_variance   | 0.249        |\n",
      "|    learning_rate        | 0.0003       |\n",
      "|    loss                 | 6.14e+03     |\n",
      "|    n_updates            | 220          |\n",
      "|    policy_gradient_loss | -0.00152     |\n",
      "|    std                  | 0.894        |\n",
      "|    value_loss           | 2.11e+04     |\n",
      "------------------------------------------\n",
      "------------------------------------------\n",
      "| rollout/                |              |\n",
      "|    ep_len_mean          | 3.45         |\n",
      "|    ep_rew_mean          | 250          |\n",
      "| time/                   |              |\n",
      "|    fps                  | 296          |\n",
      "|    iterations           | 24           |\n",
      "|    time_elapsed         | 165          |\n",
      "|    total_timesteps      | 49152        |\n",
      "| train/                  |              |\n",
      "|    approx_kl            | 0.0013366584 |\n",
      "|    clip_fraction        | 0.0216       |\n",
      "|    clip_range           | 0.2          |\n",
      "|    entropy_loss         | -1.3         |\n",
      "|    explained_variance   | 0.264        |\n",
      "|    learning_rate        | 0.0003       |\n",
      "|    loss                 | 1.45e+04     |\n",
      "|    n_updates            | 230          |\n",
      "|    policy_gradient_loss | -0.000637    |\n",
      "|    std                  | 0.889        |\n",
      "|    value_loss           | 2.22e+04     |\n",
      "------------------------------------------\n",
      "-----------------------------------------\n",
      "| rollout/                |             |\n",
      "|    ep_len_mean          | 4.06        |\n",
      "|    ep_rew_mean          | 228         |\n",
      "| time/                   |             |\n",
      "|    fps                  | 297         |\n",
      "|    iterations           | 25          |\n",
      "|    time_elapsed         | 172         |\n",
      "|    total_timesteps      | 51200       |\n",
      "| train/                  |             |\n",
      "|    approx_kl            | 0.003395676 |\n",
      "|    clip_fraction        | 0.0149      |\n",
      "|    clip_range           | 0.2         |\n",
      "|    entropy_loss         | -1.3        |\n",
      "|    explained_variance   | 0.261       |\n",
      "|    learning_rate        | 0.0003      |\n",
      "|    loss                 | 1.1e+04     |\n",
      "|    n_updates            | 240         |\n",
      "|    policy_gradient_loss | -0.00239    |\n",
      "|    std                  | 0.883       |\n",
      "|    value_loss           | 2.06e+04    |\n",
      "-----------------------------------------\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "<stable_baselines3.ppo.ppo.PPO at 0x2769f7cf7d0>"
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "env = OptimalExecutionEnv(train_df, transmat)\n",
    "model = PPO(\"MlpPolicy\", env, verbose=1)\n",
    "print(\"Entraînement en cours\")\n",
    "model.learn(total_timesteps=50000)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "4d5343e2",
   "metadata": {},
   "outputs": [],
   "source": [
    "def test_agent(model, test_df, transmat, n_episodes=5):\n",
    "    test_env = OptimalExecutionEnv(test_df, transmat)\n",
    "    all_revenues = []\n",
    "\n",
    "    for ep in range(n_episodes):\n",
    "        obs, _ = test_env.reset()\n",
    "        done = False\n",
    "        ep_revenue = 0\n",
    "        while not done:\n",
    "            action, _ = model.predict(obs, deterministic=True)\n",
    "            obs, reward, done, _, _ = test_env.step(action)\n",
    "            ep_revenue += reward * 1000 # On remet à l'échelle réelle\n",
    "        all_revenues.append(ep_revenue)\n",
    "        print(f\"Épisode {ep+1}: Revenu Total = {ep_revenue:.2f} USDT\")\n",
    "\n",
    "    # Petit graphique simple des revenus de test\n",
    "    plt.bar(range(1, n_episodes+1), all_revenues)\n",
    "    plt.title(\"Performance de l'Agent sur le set de Test\")\n",
    "    plt.ylabel(\"Revenu Total (USDT)\")\n",
    "    plt.show()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "ca0cacf2",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Évaluation de l'agent\n",
      "Épisode 1: Revenu Total = 657137.48 USDT\n",
      "Épisode 2: Revenu Total = 1090053.87 USDT\n",
      "Épisode 3: Revenu Total = 650977.65 USDT\n",
      "Épisode 4: Revenu Total = 649496.93 USDT\n",
      "Épisode 5: Revenu Total = 972410.00 USDT\n"
     ]
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAjcAAAGzCAYAAADT4Tb9AAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjkuMiwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy8hTgPZAAAACXBIWXMAAA9hAAAPYQGoP6dpAAA/3klEQVR4nO3deXxM9/7H8fcksgkJKgsRElTt+0+EqiKVi0a1VUtbYq229tBW2qJKhdtr6aK2Fl24dq3bWmqt/dpbWmoXVIJqgiBIzu+PPsztNAmZyTAcr+fjMY+H+Z7v+Z7POTOSd875nhmLYRiGAAAATMLN1QUAAAA4E+EGAACYCuEGAACYCuEGAACYCuEGAACYCuEGAACYCuEGAACYCuEGAACYCuEGAACYCuEG97T3339fpUuXlru7u6pXr+7qckzp8ccf1+OPP+608Tp16qSwsDCnjYfcexCOfVhYmDp16uTqMnCPI9zALjNmzJDFYrE+vL29Va5cOfXq1UvJyclO3db333+v119/XfXr19f06dM1cuRIp46Pu8disWjGjBnZLvvkk09ksVgUERFxd4vKpU8++STH2pF7S5Ys0TvvvOPqMqz+/rMsp4ezwuKmTZv0zjvvKCUlxSnj4dbyuboA3J/effddhYeH6+rVq9qwYYMmTpyoJUuWaO/evcqfP79TtrF69Wq5ubnps88+k6enp1PGxL1n5syZCgsL09atW3Xo0CGVLVvW1SXZ+OSTT1S0aFHOFuTRkiVLNGHChHsm4Dz22GP68ssvbdq6deumOnXq6KWXXrK2FShQwCnb27Rpk4YNG6ZOnTqpUKFCThkTOSPcwCHNmjVT7dq1Jf35A+Ghhx7S2LFj9c0336h9+/Z5Gvvy5cvKnz+/zpw5Ix8fH6cFG8MwdPXqVfn4+DhlPOTd0aNHtWnTJi1cuFA9evTQzJkzNXToUFeXdc/iPew8pUuXVunSpW3aXn75ZZUuXVovvviii6qCs3BZCk7RuHFjSX/+srrpq6++Uq1ateTj46MiRYqoXbt2OnHihM16jz/+uCpXrqwdO3boscceU/78+fXmm2/KYrFo+vTpSktLs54evnlp4MaNGxo+fLjKlCkjLy8vhYWF6c0331R6errN2GFhYXryySe1fPly1a5dWz4+Ppo8ebLWrl0ri8WiuXPnatiwYQoJCVHBggXVunVrpaamKj09Xf369VNgYKAKFCigzp07Zxl7+vTpaty4sQIDA+Xl5aWKFStq4sSJWY7LzRo2bNigOnXqyNvbW6VLl9YXX3yRpW9KSor69++vsLAweXl5qUSJEurYsaPOnTtn7ZOenq6hQ4eqbNmy8vLyUmhoqF5//fUs9eVkypQpKlOmjHx8fFSnTh2tX78+23553U5uzZw5U4ULF1aLFi3UunVrzZw5M9t+v//+uzp06CA/Pz8VKlRIsbGx+vHHH7O93LV//361bt1aRYoUkbe3t2rXrq3Fixfb9Ll5SWLjxo2Ki4tTQECAfH199fTTT+vs2bPWfmFhYfr555/1ww8/WN+Ht5ufNHv2bNWqVUsFCxaUn5+fqlSpog8++MC6/J133pHFYsmy3s2ajh07ZrP97N7D9sjMzNT48eNVqVIleXt7KygoSD169NAff/xx23WTkpLUuXNnlShRQl5eXipWrJieeuopmxolaenSpWrQoIF8fX1VsGBBtWjRQj///LN1eadOnTRhwgRJsrnkcyuGYWjEiBEqUaKE8ufPr0aNGtmM+VcpKSnq16+fQkND5eXlpbJly2r06NHKzMy87T7ezqlTp9SlSxcFBQXJy8tLlSpV0rRp07L0++ijj1SpUiXlz59fhQsXVu3atTVr1ixJf77mr732miQpPDzcuv9/P45wHs7cwCkOHz4sSXrooYckSe+9954GDx6sNm3aqFu3bjp79qw++ugjPfbYY9q1a5fNadnff/9dzZo1U7t27fTiiy8qKChItWvX1pQpU7R161Z9+umnkqR69epJ+vNM0eeff67WrVtrwIAB+u9//6uEhATt27dPixYtsqnr119/Vfv27dWjRw91795djzzyiHVZQkKCfHx8NGjQIB06dEgfffSRPDw85Obmpj/++EPvvPOOtmzZohkzZig8PFxDhgyxrjtx4kRVqlRJLVu2VL58+fSf//xHr776qjIzM9WzZ0+bGg4dOqTWrVura9euio2N1bRp09SpUyfVqlVLlSpVkiRdunRJDRo00L59+9SlSxfVrFlT586d0+LFi3Xy5EkVLVpUmZmZatmypTZs2KCXXnpJFSpU0J49ezRu3DgdOHBAX3/99S1fo88++0w9evRQvXr11K9fPx05ckQtW7ZUkSJFFBoaau2X1+3YY+bMmXrmmWfk6emp9u3ba+LEidq2bZv+7//+z6aemJgYbd26Va+88orKly+vb775RrGxsVnG+/nnn1W/fn2FhIRo0KBB8vX11dy5c9WqVSstWLBATz/9tE3/3r17q3Dhwho6dKiOHTum8ePHq1evXpozZ44kafz48erdu7cKFCigt956S5IUFBSU4/6sWLFC7du3V5MmTTR69GhJ0r59+7Rx40b17dvXoWN0q/dwbvTo0UMzZsxQ586d1adPHx09elQff/yxdu3apY0bN8rDwyPHdZ999ln9/PPP6t27t8LCwnTmzBmtWLFCiYmJ1rkoX375pWJjYxUdHa3Ro0fr8uXLmjhxoh599FHt2rVLYWFh6tGjh3777TetWLEiy6WgnAwZMkQjRoxQ8+bN1bx5c+3cuVNNmzbVtWvXbPpdvnxZDRs21KlTp9SjRw+VLFlSmzZtUnx8vE6fPq3x48fbdbz+Kjk5WXXr1pXFYlGvXr0UEBCgpUuXqmvXrrpw4YL69esnSZo6dar69Omj1q1bq2/fvrp69ap++ukn/fe//9Xzzz+vZ555RgcOHNC///1vjRs3TkWLFpUkBQQEOFwbbsMA7DB9+nRDkrFy5Urj7NmzxokTJ4zZs2cbDz30kOHj42OcPHnSOHbsmOHu7m689957Nuvu2bPHyJcvn017w4YNDUnGpEmTsmwrNjbW8PX1tWnbvXu3Icno1q2bTfvAgQMNScbq1autbaVKlTIkGcuWLbPpu2bNGkOSUblyZePatWvW9vbt2xsWi8Vo1qyZTf/IyEijVKlSNm2XL1/OUm90dLRRunRpm7abNaxbt87adubMGcPLy8sYMGCAtW3IkCGGJGPhwoVZxs3MzDQMwzC+/PJLw83NzVi/fr3N8kmTJhmSjI0bN2ZZ96Zr164ZgYGBRvXq1Y309HRr+5QpUwxJRsOGDa1tedmOYfz5uv39eGVn+/bthiRjxYoV1v0sUaKE0bdvX5t+CxYsMCQZ48ePt7ZlZGQYjRs3NiQZ06dPt7Y3adLEqFKlinH16lVrW2ZmplGvXj3j4YcftrbdfB9HRUVZj69hGEb//v0Nd3d3IyUlxdpWqVIlm+NzK3379jX8/PyMGzdu5Nhn6NChRnY/em/WdPToUWtbTu/hnPz92K9fv96QZMycOdOm37Jly7Jt/6s//vjDkGS8//77Ofa5ePGiUahQIaN79+427UlJSYa/v79Ne8+ePbPd7+ycOXPG8PT0NFq0aGHz+rz55puGJCM2NtbaNnz4cMPX19c4cOCAzRiDBg0y3N3djcTExFxt0zAMw9fX12bsrl27GsWKFTPOnTtn069du3aGv7+/9efAU089ZVSqVOmWY7///vtZXl/cOVyWgkOioqIUEBCg0NBQtWvXTgUKFNCiRYsUEhKihQsXKjMzU23atNG5c+esj+DgYD388MNas2aNzVheXl7q3Llzrra7ZMkSSVJcXJxN+4ABAyRJ3333nU17eHi4oqOjsx2rY8eONn+1RkREyDAMdenSxaZfRESETpw4oRs3bljb/jrnITU1VefOnVPDhg115MgRpaam2qxfsWJFNWjQwPo8ICBAjzzyiI4cOWJtW7BggapVq5blzIIk6+n7efPmqUKFCipfvrzNcb15SfDvx/Wvtm/frjNnzujll1+2mcPUqVMn+fv72/TNy3bsMXPmTAUFBalRo0bW/Wzbtq1mz56tjIwMa79ly5bJw8ND3bt3t7a5ubllOUN2/vx5rV69Wm3atNHFixetdf/++++Kjo7WwYMHderUKZt1XnrpJZvLIw0aNFBGRoaOHz/u0D4VKlRIaWlpWrFihUPrZ+dW7+HbmTdvnvz9/fXEE0/YvJa1atVSgQIFbvla3pzvtnbt2hwvYa1YsUIpKSlq3769zfju7u6KiIhw+L2ycuVKXbt2Tb1797Z5fW6eKfn7PjZo0ECFCxe2qSEqKkoZGRlat26dQzUYhqEFCxYoJiZGhmHYjB0dHa3U1FTt3LlT0p+v+8mTJ7Vt2zaHtgXne6AvS61bt07vv/++duzYodOnT2vRokVq1aqVXWMYhqExY8ZoypQpOn78uIoWLapXX33VegrbrCZMmKBy5copX758CgoK0iOPPCI3tz+z8sGDB2UYhh5++OFs1/37afCQkJBcTxo+fvy43NzcstxRExwcrEKFCmX5pRQeHp7jWCVLlrR5fvOX/F8v0dxsz8zMVGpqqvWy28aNGzV06FBt3rxZly9ftumfmppqExj+vh1JKly4sM0vjMOHD+vZZ5/NsVbpz+O6b9++HE9lnzlzJsd1bx6Xv78mHh4eWSZV5mU7uZWRkaHZs2erUaNGNvO0IiIiNGbMGK1atUpNmza11l6sWLEsd+H9/T1w6NAhGYahwYMHa/DgwTnWHhISYn3+99emcOHCkpSr+SjZefXVVzV37lw1a9ZMISEhatq0qdq0aaN//OMfDo0n3fo9fDsHDx5UamqqAgMDs11+q9fSy8tLo0eP1oABAxQUFKS6devqySefVMeOHRUcHGwdX/rfnLu/8/Pzc6junN6vAQEB1tfopoMHD+qnn35y+vv17NmzSklJ0ZQpUzRlypRbjv3GG29o5cqVqlOnjsqWLaumTZvq+eefV/369R3aNvLugQ43aWlpqlatmrp06aJnnnnGoTH69u2r77//Xv/6179UpUoVnT9/XufPn3dypfeeOnXqWO+W+rvMzExZLBYtXbpU7u7uWZb//dZKR+78uN1kxNyMnV1tt2o3DEPSn0GkSZMmKl++vMaOHavQ0FB5enpqyZIlGjduXJZJjLcbL7cyMzNVpUoVjR07Ntvlfw9ljrob21m9erVOnz6t2bNna/bs2VmWz5w50xpucuvmcR84cGCOZzr+Hoic9drcFBgYqN27d2v58uVaunSpli5dqunTp6tjx476/PPPJeX83v3r2aq/ysudUZmZmQoMDMxxovbt5nz069dPMTEx+vrrr7V8+XINHjxYCQkJWr16tWrUqGE95l9++aU18PxVvnx3/ldMZmamnnjiCb3++uvZLi9XrpzD40rSiy++mO38LkmqWrWqJKlChQr69ddf9e2332rZsmVasGCBPvnkEw0ZMkTDhg1zaPvImwc63DRr1kzNmjXLcXl6erreeust/fvf/1ZKSooqV66s0aNHW++W2LdvnyZOnKi9e/daJ/nl5a8ssyhTpowMw1B4eLjDP1hyUqpUKWVmZurgwYOqUKGCtT05OVkpKSkqVaqUU7eXnf/85z9KT0/X4sWLbf7yz8vlmjJlymjv3r237fPjjz+qSZMmuQ53N908LgcPHrT5K/v69es6evSoqlWr5pTt5NbMmTMVGBhovYPmrxYuXKhFixZp0qRJ8vHxUalSpbRmzRrrRwTcdOjQIZv1bp6B8vDwUFRUlNNqtfcYeHp6KiYmRjExMcrMzNSrr76qyZMna/DgwSpbtqz1zENKSorNxHpHL4XdSpkyZbRy5UrVr1/f4ZBUpkwZDRgwQAMGDNDBgwdVvXp1jRkzRl999ZXKlCkj6c9Qd7tjbs9x/Ov79a9nFs+ePZvlrFqZMmV06dIlp77m0p/Br2DBgsrIyMjV2L6+vmrbtq3atm2ra9eu6ZlnntF7772n+Ph4eXt737H/S8gec25uoVevXtq8ebNmz56tn376Sc8995z+8Y9/WE/F/uc//1Hp0qX17bffKjw8XGFhYerWrdsDcebmVp555hm5u7tr2LBhWf4CNgxDv//+u8NjN2/eXJKy3AFx8yxDixYtHB47t27+tf/XfUtNTdX06dMdHvPZZ5/Vjz/+mOVur79up02bNjp16pSmTp2apc+VK1eUlpaW4/i1a9dWQECAJk2aZHO3yYwZM7J8YmpetpMbV65c0cKFC/Xkk0+qdevWWR69evXSxYsXrbdvR0dH6/r16zb1ZGZmZglGgYGBevzxxzV58mSdPn06y3b/eou3PXx9fXP9qbJ/f2+7ublZ/7q/eRv9zUDw17kgaWlp1jM7ztSmTRtlZGRo+PDhWZbduHHjlvt1+fJlXb161aatTJkyKliwoHVfoqOj5efnp5EjR+r69etZxvjrMff19ZWkXB3LqKgoeXh46KOPPrL5f5bdnU9t2rTR5s2btXz58izLUlJSbObK2cPd3V3PPvusFixYkO0fHn/dt7+/7p6enqpYsaIMw7AeF3v2H3n3QJ+5uZXExERNnz5diYmJKl68uKQ/T3cvW7bM+lUAR44c0fHjxzVv3jx98cUXysjIUP/+/dW6dWutXr3axXvgOmXKlNGIESMUHx+vY8eOqVWrVipYsKCOHj2qRYsW6aWXXtLAgQMdGrtatWqKjY3VlClTlJKSooYNG2rr1q36/PPP1apVK+vk1DupadOm1r/Oe/TooUuXLmnq1KkKDAzM9pdqbrz22muaP3++nnvuOXXp0kW1atXS+fPntXjxYk2aNEnVqlVThw4dNHfuXL388stas2aN6tevr4yMDO3fv19z5861fhZKdjw8PDRixAj16NFDjRs3Vtu2bXX06FFNnz49y5ybvGwnNxYvXqyLFy+qZcuW2S6vW7euAgICNHPmTLVt21atWrVSnTp1NGDAAB06dEjly5fX4sWLrX9E/PUv4gkTJujRRx9VlSpV1L17d5UuXVrJycnavHmzTp48qR9//NHuemvVqqWJEydqxIgRKlu2rAIDA3OcY3Lzj5vGjRurRIkSOn78uD766CNVr17deqaxadOmKlmypLp27arXXntN7u7umjZtmgICApSYmGh3fbfSsGFD9ejRQwkJCdq9e7eaNm0qDw8PHTx4UPPmzdMHH3yg1q1bZ7vugQMH1KRJE7Vp00YVK1ZUvnz5tGjRIiUnJ6tdu3aS/pxTM3HiRHXo0EE1a9ZUu3btrPvx3XffqX79+vr444+tx1GS+vTpo+joaLm7u1vH+buAgAANHDhQCQkJevLJJ9W8eXPt2rVLS5cutd5GfdNrr72mxYsX68knn7R+xEJaWpr27Nmj+fPn69ixY1nWya1Ro0ZpzZo1ioiIUPfu3VWxYkWdP39eO3fu1MqVK63vwaZNmyo4OFj169dXUFCQ9u3bp48//lgtWrRQwYIFbfb/rbfeUrt27eTh4aGYmBhr6IGT3f0btO5NkoxFixZZn3/77beGJMPX19fmkS9fPqNNmzaGYRhG9+7dDUnGr7/+al1vx44dhiRj//79d3sX7oqbt6tu27bttn0XLFhgPProo9ZjV758eaNnz542x6thw4Y53kKZ3a3ghmEY169fN4YNG2aEh4cbHh4eRmhoqBEfH29z+69h/HkbbYsWLbKsf/NW8Hnz5uVq327eunv27Flr2+LFi42qVasa3t7eRlhYmDF69Ghj2rRp2d7Km10NDRs2zHJ78e+//2706tXLCAkJMTw9PY0SJUoYsbGxNrehXrt2zRg9erRRqVIlw8vLyyhcuLBRq1YtY9iwYUZqamrWg/g3n3zyiREeHm54eXkZtWvXNtatW5dtLXnZzu1uBY+JiTG8vb2NtLS0HPt06tTJ8PDwsO772bNnjeeff94oWLCg4e/vb3Tq1MnYuHGjIcmYPXu2zbqHDx82OnbsaAQHBxseHh5GSEiI8eSTTxrz58+39snptb753lizZo21LSkpyWjRooVRsGDBLLfN/938+fONpk2bGoGBgYanp6dRsmRJo0ePHsbp06dt+u3YscOIiIiw9hk7dmyOt4Jn9/7JSU7HfsqUKUatWrUMHx8fo2DBgkaVKlWM119/3fjtt99yHOvcuXNGz549jfLlyxu+vr6Gv7+/ERERYcydOzdL3zVr1hjR0dGGv7+/4e3tbZQpU8bo1KmTsX37dmufGzduGL179zYCAgIMi8Vy29vCMzIyjGHDhhnFihUzfHx8jMcff9zYu3evUapUKZvbtQ3jz1vS4+PjjbJlyxqenp5G0aJFjXr16hn/+te/bD7u4Xb+fiu4YRhGcnKy0bNnTyM0NNTw8PAwgoODjSZNmhhTpkyx9pk8ebLx2GOPGQ899JDh5eVllClTxnjttdey/F8ZPny4ERISYri5uXFb+B1mMQwHZ86ZjMVisblbas6cOXrhhRf0888/Z5l0WKBAAQUHB2vo0KFZTsdeuXJF+fPn1/fff68nnnjibu4C8ED5+uuv9fTTT2vDhg3clQLABpelclCjRg1lZGTozJkzNp9R8lf169fXjRs3dPjwYet19AMHDkjSXZnYCjworly5YjMhNiMjQx999JH8/PxUs2ZNF1YG4F70QIebS5cu2dxxcfToUe3evVtFihRRuXLl9MILL6hjx44aM2aMatSoobNnz2rVqlWqWrWqWrRooaioKNWsWVNdunTR+PHjrR+9/8QTTzj9LiHgQda7d29duXJFkZGRSk9P18KFC7Vp0yaNHDmSL5EEkMUDfVlq7dq12U5AjY2N1YwZM3T9+nWNGDFCX3zxhU6dOqWiRYuqbt26GjZsmKpUqSJJ+u2339S7d299//338vX1VbNmzTRmzBgVKVLkbu8OYFqzZs3SmDFjdOjQIV29elVly5bVK6+8ol69erm6NAD3oAc63AAAAPPhc24AAICpEG4AAICpPHATijMzM/Xbb7+pYMGCfBw2AAD3CcMwdPHiRRUvXtz6Rc05eeDCzW+//ea0LxgEAAB314kTJ1SiRIlb9nngws3Nj8I+ceKE/Pz8XFwNAADIjQsXLig0NNT6e/xWHrhwc/NSlJ+fH+EGAID7TG6mlDChGAAAmArhBgAAmArhBgAAmArhBgAAmArhBgAAmArhBgAAmArhBgAAmArhBgAAmArhBgAAmArhBgAAmArhBgAAmArhBgAAmArhBgAAmArhBgAAmEo+VxcAOEPYoO9cXcJ949ioFq4uAQDuKM7cAAAAUyHcAAAAUyHcAAAAUyHcAAAAUyHcAAAAUyHcAAAAUyHcAAAAUyHcAAAAUyHcAAAAUyHcAAAAUyHcAAAAUyHcAAAAUyHcAAAAUyHcAAAAUyHcAAAAUyHcAAAAUyHcAAAAUyHcAAAAUyHcAAAAUyHcAAAAUyHcAAAAUyHcAAAAUyHcAAAAUyHcAAAAUyHcAAAAU3FpuFm3bp1iYmJUvHhxWSwWff3117ddZ+3atapZs6a8vLxUtmxZzZgx447XCQAA7h8uDTdpaWmqVq2aJkyYkKv+R48eVYsWLdSoUSPt3r1b/fr1U7du3bR8+fI7XCkAALhf5HPlxps1a6ZmzZrluv+kSZMUHh6uMWPGSJIqVKigDRs2aNy4cYqOjs52nfT0dKWnp1ufX7hwIW9FAwCAe9p9Nedm8+bNioqKsmmLjo7W5s2bc1wnISFB/v7+1kdoaOidLhMAALjQfRVukpKSFBQUZNMWFBSkCxcu6MqVK9muEx8fr9TUVOvjxIkTd6NUAADgIi69LHU3eHl5ycvLy9VlAACAu+S+OnMTHBys5ORkm7bk5GT5+fnJx8fHRVUBAIB7yX0VbiIjI7Vq1SqbthUrVigyMtJFFQEAgHuNS8PNpUuXtHv3bu3evVvSn7d67969W4mJiZL+nC/TsWNHa/+XX35ZR44c0euvv679+/frk08+0dy5c9W/f39XlA8AAO5BLg0327dvV40aNVSjRg1JUlxcnGrUqKEhQ4ZIkk6fPm0NOpIUHh6u7777TitWrFC1atU0ZswYffrppzneBg4AAB48FsMwDFcXcTdduHBB/v7+Sk1NlZ+fn6vLgZOEDfrO1SXcN46NauHqEgDAbvb8/r6v5twAAADcjulvBQcAwBk4Q5x7rj5DzJkbAABgKoQbAABgKoQbAABgKoQbAABgKoQbAABgKoQbAABgKoQbAABgKoQbAABgKoQbAABgKoQbAABgKoQbAABgKoQbAABgKoQbAABgKoQbAABgKoQbAABgKoQbAABgKoQbAABgKoQbAABgKoQbAABgKoQbAABgKoQbAABgKoQbAABgKoQbAABgKoQbAABgKoQbAABgKoQbAABgKoQbAABgKoQbAABgKoQbAABgKoQbAABgKoQbAABgKoQbAABgKoQbAABgKoQbAABgKoQbAABgKoQbAABgKoQbAABgKoQbAABgKoQbAABgKoQbAABgKoQbAABgKoQbAABgKoQbAABgKoQbAABgKoQbAABgKoQbAABgKoQbAABgKoQbAABgKoQbAABgKoQbAABgKoQbAABgKi4PNxMmTFBYWJi8vb0VERGhrVu33rL/+PHj9cgjj8jHx0ehoaHq37+/rl69epeqBQAA9zqXhps5c+YoLi5OQ4cO1c6dO1WtWjVFR0frzJkz2fafNWuWBg0apKFDh2rfvn367LPPNGfOHL355pt3uXIAAHCvcmm4GTt2rLp3767OnTurYsWKmjRpkvLnz69p06Zl23/Tpk2qX7++nn/+eYWFhalp06Zq3779bc/2AACAB4fLws21a9e0Y8cORUVF/a8YNzdFRUVp8+bN2a5Tr1497dixwxpmjhw5oiVLlqh58+Y5bic9PV0XLlyweQAAAPPK56oNnzt3ThkZGQoKCrJpDwoK0v79+7Nd5/nnn9e5c+f06KOPyjAM3bhxQy+//PItL0slJCRo2LBhTq0dAADcu1w+odgea9eu1ciRI/XJJ59o586dWrhwob777jsNHz48x3Xi4+OVmppqfZw4ceIuVgwAAO42l525KVq0qNzd3ZWcnGzTnpycrODg4GzXGTx4sDp06KBu3bpJkqpUqaK0tDS99NJLeuutt+TmljWreXl5ycvLy/k7AAAA7kkuO3Pj6empWrVqadWqVda2zMxMrVq1SpGRkdmuc/ny5SwBxt3dXZJkGMadKxYAANw3XHbmRpLi4uIUGxur2rVrq06dOho/frzS0tLUuXNnSVLHjh0VEhKihIQESVJMTIzGjh2rGjVqKCIiQocOHdLgwYMVExNjDTkAAODBZne42bdvn2bPnq3169fr+PHjunz5sgICAlSjRg1FR0fr2WefzfVloLZt2+rs2bMaMmSIkpKSVL16dS1btsw6yTgxMdHmTM3bb78ti8Wit99+W6dOnVJAQIBiYmL03nvv2bsbAADApCxGLq/n7Ny5U6+//ro2bNig+vXrq06dOipevLh8fHx0/vx57d27V+vXr9eFCxf0+uuvq1+/fvfkXJcLFy7I399fqamp8vPzc3U5cJKwQd+5uoT7xrFRLVxdAnBf4udM7t2JnzP2/P7O9ZmbZ599VgMHDtT8+fNVqFChHPtt3rxZH3zwgcaMGcMnBwMAgLsu1+HmwIED8vDwuG2/yMhIRUZG6vr163kqDAAAwBG5vlvKw8NDjRs3VkpKSq77AwAA3G123Qq+du1aXbt27U7VAgAAkGf31ScUAwAA3I7dt4L/8ssvSkpKumWfqlWrOlwQAABAXtgdbpo0aZLtpwFbLBYZhiGLxaKMjAynFAcAAGAvu8PNf//7XwUEBNyJWgAAAPLM7nBTsmRJBQYG3olaAAAA8owJxQAAwFTsCjcNGzaUp6fnnaoFAAAgz+y6LLVmzRpJkmEY2rFjh44dOyaLxaLw8HDVqFFDFovljhQJAACQW3bPuVmzZo26du2q48ePW++auhlwpk2bpscee8zpRQIAAOSWXZelDh06pCeffFJhYWFauHCh9u3bp19++UXz5s1TiRIl1Lx5cx05cuRO1QoAAHBbdp25GT9+vOrWratVq1bZtJcvX15PP/20oqKiNG7cOH300UdOLRIAACC37P5uqX79+mW7zGKxqF+/ftZ5OQAAAK5gV7hJTExUlSpVclxeuXJlHT9+PM9FAQAAOMqucHPp0iXlz58/x+X58+fX5cuX81wUAACAo5z6xZnnzp3Lc0EAAAB5cUe+OBMAAMBV7Ao3R48evVN1AAAAOIVd4aZUqVJ3qg4AAACnsGtC8blz57LcDfXzzz+rc+fOatOmjWbNmuXU4gAAAOxlV7jp3bu3PvzwQ+vzM2fOqEGDBtq2bZvS09PVqVMnffnll04vEgAAILfsCjdbtmxRy5Ytrc+/+OILFSlSRLt379Y333yjkSNHasKECU4vEgAAILfsCjdJSUkKCwuzPl+9erWeeeYZ5cv359Sdli1b6uDBg04tEAAAwB52hRs/Pz+lpKRYn2/dulURERHW5xaLRenp6U4rDgAAwF52hZu6devqww8/VGZmpubPn6+LFy+qcePG1uUHDhxQaGio04sEAADILbtuBR8+fLiaNGmir776Sjdu3NCbb76pwoULW5fPnj1bDRs2dHqRAAAAuWVXuKlatar27dunjRs3Kjg42OaSlCS1a9dOFStWdGqBAAAA9rD76xeKFi2qp556KttlLVq0yHNBAAAAeWFXuImLi8u23d/fX+XKldMzzzwjLy8vpxQGAADgCLvCza5du7JtT0lJ0aFDhzR48GCtXr1aJUuWdEpxAAAA9rIr3KxZsybHZRcuXNALL7ygQYMG8TUMAADAZey6FfxW/Pz8NHjwYG3cuNFZQwIAANjNaeFG+nOy8fnz5505JAAAgF2cGm62bNmiMmXKOHNIAAAAu9g15+ann37Ktj01NVU7duzQyJEjNXToUKcUBgAA4Ai7wk316tVlsVhkGEaWZUWLFlVcXJxeffVVpxUHAABgL7vCzdGjR7Nt9/Pzs/kahgdZ2KDvXF3CfePYKD70EQDgfHaFm1KlSt2pOgAAAJwi1+Fmy5Ytqlu3bq76Xr58WUePHlWlSpUcLgzAvY8zlbnHmUrg7sl1uOnQoYNKly6tbt26qXnz5vL19c3S55dfftFXX32l6dOna/To0YQbALgDCJW5R6h8MOU63Pzyyy+aOHGi3n77bT3//PMqV66cihcvLm9vb/3xxx/av3+/Ll26pKefflrff/+9qlSpcifrBgAAyFauw42Hh4f69OmjPn36aPv27dqwYYOOHz+uK1euqFq1aurfv78aNWqkIkWK3Ml6AQAAbsmuCcU31a5dW7Vr13Z2LQAAAHnm1E8oBgAAcDXCDQAAMBXCDQAAMBXCDQAAMBXCDQAAMJVc3y314Ycf5nrQPn36OFQMAABAXuU63IwbNy5X/SwWC+EGAAC4TK7DTU7fCA4AAHAvcfmcmwkTJigsLEze3t6KiIjQ1q1bb9k/JSVFPXv2VLFixeTl5aVy5cppyZIld6laAABwr3PoE4ol6eTJk1q8eLESExN17do1m2Vjx47N1Rhz5sxRXFycJk2apIiICI0fP17R0dH69ddfFRgYmKX/tWvX9MQTTygwMFDz589XSEiIjh8/rkKFCjm6GwAAwGQcCjerVq1Sy5YtVbp0ae3fv1+VK1fWsWPHZBiGatasmetxxo4dq+7du6tz586SpEmTJum7777TtGnTNGjQoCz9p02bpvPnz2vTpk3y8PCQJIWFhTmyCwAAwKQcuiwVHx+vgQMHas+ePfL29taCBQt04sQJNWzYUM8991yuxrh27Zp27NihqKio/xXj5qaoqCht3rw523UWL16syMhI9ezZU0FBQapcubJGjhypjIyMHLeTnp6uCxcu2DwAAIB5ORRu9u3bp44dO0qS8uXLpytXrqhAgQJ69913NXr06FyNce7cOWVkZCgoKMimPSgoSElJSdmuc+TIEc2fP18ZGRlasmSJBg8erDFjxmjEiBE5bichIUH+/v7WR2hoaC73EgAA3I8cCje+vr7WeTbFihXT4cOHrcvOnTvnnMqykZmZqcDAQE2ZMkW1atVS27Zt9dZbb2nSpEk5rhMfH6/U1FTr48SJE3esPgAA4HoOzbmpW7euNmzYoAoVKqh58+YaMGCA9uzZo4ULF6pu3bq5GqNo0aJyd3dXcnKyTXtycrKCg4OzXadYsWLy8PCQu7u7ta1ChQpKSkrStWvX5OnpmWUdLy8veXl52bF3AADgfubQmZuxY8cqIiJCkjRs2DA1adJEc+bMUVhYmD777LNcjeHp6alatWpp1apV1rbMzEytWrVKkZGR2a5Tv359HTp0SJmZmda2AwcOqFixYtkGGwAA8OBx6MxN6dKlrf/29fW95WWhW4mLi1NsbKxq166tOnXqaPz48UpLS7PePdWxY0eFhIQoISFBkvTKK6/o448/Vt++fdW7d28dPHhQI0eO5BORAQCAlcPhZtu2bXrooYds2lNSUlSzZk0dOXIkV+O0bdtWZ8+e1ZAhQ5SUlKTq1atr2bJl1knGiYmJcnP738ml0NBQLV++XP3791fVqlUVEhKivn376o033nBkNwAAgAk5FG6OHTuW7e3X6enpOnXqlF1j9erVS7169cp22dq1a7O0RUZGasuWLXZtAwAAPDjsCjeLFy+2/nv58uXy9/e3Ps/IyNCqVav4UD0AAOBSdoWbVq1aSfrzm79jY2Ntlnl4eCgsLExjxoxxWnEAAAD2sivc3LxLKTw8XNu2bVPRokXvSFEAAACOcmjOzdGjR51dBwAAgFM49Dk3kvTDDz8oJiZGZcuWVdmyZdWyZUutX7/embUBAADYzaFw89VXXykqKkr58+dXnz591KdPH/n4+KhJkyaaNWuWs2sEAADINYcuS7333nv65z//qf79+1vb+vTpo7Fjx2r48OF6/vnnnVYgAACAPRw6c3PkyBHFxMRkaW/ZsiXzcQAAgEs5FG5CQ0NtvhPqppUrVyo0NDTPRQEAADjKrstSXbp00QcffKABAwaoT58+2r17t+rVqydJ2rhxo2bMmKEPPvjgjhQKAACQG3aFm88//1yjRo3SK6+8ouDgYI0ZM0Zz586VJFWoUEFz5szRU089dUcKBQAAyA27wo1hGNZ/P/3003r66aedXhAAAEBe2H231MWLF+Xt7X3LPn5+fg4XBAAAkBd2h5ty5crluMwwDFkslmy/MRwAAOBusDvczJ8/X0WKFLkTtQAAAOSZ3eGmfv36CgwMvBO1AAAA5JnD3y0FAABwL7Ir3JQqVUru7u53qhYAAIA8s+uyFF+tAAAA7nVclgIAAKZCuAEAAKZCuAEAAKZCuAEAAKZi9+fcSNK77757y+VDhgxxqBgAAIC8cijcLFq0yOb59evXdfToUeXLl09lypQh3AAAAJdxKNzs2rUrS9uFCxfUqVMnvikcAAC4lNPm3Pj5+WnYsGEaPHiws4YEAACwm1MnFKempio1NdWZQwIAANjFoctSH374oc1zwzB0+vRpffnll2rWrJlTCgMAAHCEQ+Fm3LhxNs/d3NwUEBCg2NhYxcfHO6UwAAAARzgUbviOKQAAcK/iQ/wAAICpOHTmJi0tTaNGjdKqVat05swZZWZm2iw/cuSIU4oDAACwl0Phplu3bvrhhx/UoUMHFStWTBaLxdl1AQAAOMShcLN06VJ99913ql+/vrPrAQAAyBOH5twULlxYRYoUcXYtAAAAeeZQuBk+fLiGDBmiy5cvO7seAACAPHHostSYMWN0+PBhBQUFKSwsTB4eHjbLd+7c6ZTiAAAA7OVQuGnVqpWTywAAAHAOh8LN0KFDnV0HAACAUzj8IX4pKSn69NNPFR8fr/Pnz0v683LUqVOnnFYcAACAvRw6c/PTTz8pKipK/v7+OnbsmLp3764iRYpo4cKFSkxM1BdffOHsOgEAAHLFoTM3cXFx6tSpkw4ePChvb29re/PmzbVu3TqnFQcAAGAvh8LNtm3b1KNHjyztISEhSkpKynNRAAAAjnIo3Hh5eenChQtZ2g8cOKCAgIA8FwUAAOAoh8JNy5Yt9e677+r69euSJIvFosTERL3xxht69tlnnVogAACAPRwKN2PGjNGlS5cUGBioK1euqGHDhipbtqwKFiyo9957z9k1AgAA5JpDd0v5+/trxYoV2rBhg3766SddunRJNWvWVFRUlLPrAwAAsItD4ebEiRMKDQ3Vo48+qkcffdTZNQEAADjMoctSYWFhatiwoaZOnao//vjD2TUBAAA4zKFws337dtWpU0fvvvuuihUrplatWmn+/PlKT093dn0AAAB2cSjc1KhRQ++//74SExO1dOlSBQQE6KWXXlJQUJC6dOni7BoBAAByzeHvlpL+vAW8UaNGmjp1qlauXKnw8HB9/vnnzqoNAADAbnkKNydPntQ///lPVa9eXXXq1FGBAgU0YcIEu8eZMGGCwsLC5O3trYiICG3dujVX682ePVsWi0WtWrWye5sAAMCcHAo3kydPVsOGDRUWFqYvvvhCbdu21eHDh7V+/Xq9/PLLdo01Z84cxcXFaejQodq5c6eqVaum6OhonTlz5pbrHTt2TAMHDlSDBg0c2QUAAGBSDoWbESNGKCIiQjt27NDevXsVHx+vUqVKOVTA2LFj1b17d3Xu3FkVK1bUpEmTlD9/fk2bNi3HdTIyMvTCCy9o2LBhKl26tEPbBQAA5uTQ59wkJibKYrHkeePXrl3Tjh07FB8fb21zc3NTVFSUNm/enON67777rgIDA9W1a1etX7/+lttIT0+3uYsru+/EAgAA5uHQmRuLxaL169frxRdfVGRkpE6dOiVJ+vLLL7Vhw4Zcj3Pu3DllZGQoKCjIpj0oKCjHbxffsGGDPvvsM02dOjVX20hISJC/v7/1ERoamuv6AADA/cehcLNgwQJFR0fLx8dHu3btsp4ZSU1N1ciRI51a4F9dvHhRHTp00NSpU1W0aNFcrRMfH6/U1FTr48SJE3esPgAA4HoOXZYaMWKEJk2apI4dO2r27NnW9vr162vEiBG5Hqdo0aJyd3dXcnKyTXtycrKCg4Oz9D98+LCOHTummJgYa1tmZqYkKV++fPr1119VpkwZm3W8vLzk5eWV65oAAMD9zaEzN7/++qsee+yxLO3+/v5KSUnJ9Tienp6qVauWVq1aZW3LzMzUqlWrFBkZmaV/+fLltWfPHu3evdv6aNmypRo1aqTdu3dzyQkAADh25iY4OFiHDh1SWFiYTfuGDRvsvnspLi5OsbGxql27turUqaPx48crLS1NnTt3liR17NhRISEhSkhIkLe3typXrmyzfqFChSQpSzsAAHgwORRuunfvrr59+2ratGmyWCz67bfftHnzZg0cOFCDBw+2a6y2bdvq7NmzGjJkiJKSklS9enUtW7bMOsk4MTFRbm55+qxBAADwAHEo3AwaNEiZmZlq0qSJLl++rMcee0xeXl4aOHCgevfubfd4vXr1Uq9evbJdtnbt2luuO2PGDLu3BwAAzMuhcGOxWPTWW2/ptdde06FDh3Tp0iVVrFhRBQoU0JUrV+Tj4+PsOgEAAHIlT9d7PD09VbFiRdWpU0ceHh4aO3aswsPDnVUbAACA3ewKN+np6YqPj1ft2rVVr149ff3115Kk6dOnKzw8XOPGjVP//v3vRJ0AAAC5YtdlqSFDhmjy5MmKiorSpk2b9Nxzz6lz587asmWLxo4dq+eee07u7u53qlYAAIDbsivczJs3T1988YVatmypvXv3qmrVqrpx44Z+/PFHp3zXFAAAQF7ZdVnq5MmTqlWrlqQ/P1fGy8tL/fv3J9gAAIB7hl3hJiMjQ56entbn+fLlU4ECBZxeFAAAgKPsuixlGIY6depk/a6mq1ev6uWXX5avr69Nv4ULFzqvQgAAADvYFW5iY2Ntnr/44otOLQYAACCv7Ao306dPv1N1AAAAOAVf2gQAAEyFcAMAAEyFcAMAAEyFcAMAAEyFcAMAAEyFcAMAAEyFcAMAAEyFcAMAAEyFcAMAAEyFcAMAAEyFcAMAAEyFcAMAAEyFcAMAAEyFcAMAAEyFcAMAAEyFcAMAAEyFcAMAAEyFcAMAAEyFcAMAAEyFcAMAAEyFcAMAAEyFcAMAAEyFcAMAAEyFcAMAAEyFcAMAAEyFcAMAAEyFcAMAAEyFcAMAAEyFcAMAAEyFcAMAAEyFcAMAAEyFcAMAAEyFcAMAAEyFcAMAAEyFcAMAAEyFcAMAAEyFcAMAAEyFcAMAAEyFcAMAAEyFcAMAAEyFcAMAAEyFcAMAAEyFcAMAAEyFcAMAAEzlngg3EyZMUFhYmLy9vRUREaGtW7fm2Hfq1Klq0KCBChcurMKFCysqKuqW/QEAwIPF5eFmzpw5iouL09ChQ7Vz505Vq1ZN0dHROnPmTLb9165dq/bt22vNmjXavHmzQkND1bRpU506deouVw4AAO5FLg83Y8eOVffu3dW5c2dVrFhRkyZNUv78+TVt2rRs+8+cOVOvvvqqqlevrvLly+vTTz9VZmamVq1adZcrBwAA9yKXhptr165px44dioqKsra5ubkpKipKmzdvztUYly9f1vXr11WkSJFsl6enp+vChQs2DwAAYF4uDTfnzp1TRkaGgoKCbNqDgoKUlJSUqzHeeOMNFS9e3CYg/VVCQoL8/f2tj9DQ0DzXDQAA7l0uvyyVF6NGjdLs2bO1aNEieXt7Z9snPj5eqamp1seJEyfucpUAAOBuyufKjRctWlTu7u5KTk62aU9OTlZwcPAt1/3Xv/6lUaNGaeXKlapatWqO/by8vOTl5eWUegEAwL3PpWduPD09VatWLZvJwDcnB0dGRua43j//+U8NHz5cy5YtU+3ate9GqQAA4D7h0jM3khQXF6fY2FjVrl1bderU0fjx45WWlqbOnTtLkjp27KiQkBAlJCRIkkaPHq0hQ4Zo1qxZCgsLs87NKVCggAoUKOCy/QAAAPcGl4ebtm3b6uzZsxoyZIiSkpJUvXp1LVu2zDrJODExUW5u/zvBNHHiRF27dk2tW7e2GWfo0KF655137mbpAADgHuTycCNJvXr1Uq9evbJdtnbtWpvnx44du/MFAQCA+9Z9fbcUAADA3xFuAACAqRBuAACAqRBuAACAqRBuAACAqRBuAACAqRBuAACAqRBuAACAqRBuAACAqRBuAACAqRBuAACAqRBuAACAqRBuAACAqRBuAACAqRBuAACAqRBuAACAqRBuAACAqRBuAACAqRBuAACAqRBuAACAqRBuAACAqRBuAACAqRBuAACAqRBuAACAqRBuAACAqRBuAACAqRBuAACAqRBuAACAqRBuAACAqRBuAACAqRBuAACAqRBuAACAqRBuAACAqRBuAACAqRBuAACAqRBuAACAqRBuAACAqRBuAACAqRBuAACAqRBuAACAqRBuAACAqRBuAACAqRBuAACAqRBuAACAqRBuAACAqRBuAACAqRBuAACAqRBuAACAqRBuAACAqRBuAACAqRBuAACAqRBuAACAqRBuAACAqdwT4WbChAkKCwuTt7e3IiIitHXr1lv2nzdvnsqXLy9vb29VqVJFS5YsuUuVAgCAe53Lw82cOXMUFxenoUOHaufOnapWrZqio6N15syZbPtv2rRJ7du3V9euXbVr1y61atVKrVq10t69e+9y5QAA4F7k8nAzduxYde/eXZ07d1bFihU1adIk5c+fX9OmTcu2/wcffKB//OMfeu2111ShQgUNHz5cNWvW1Mcff3yXKwcAAPeifK7c+LVr17Rjxw7Fx8db29zc3BQVFaXNmzdnu87mzZsVFxdn0xYdHa2vv/462/7p6elKT0+3Pk9NTZUkXbhwIY/VZy8z/fIdGdeMnPkacNxzj+PuGhx31+C4u8ad+B17c0zDMG7b16Xh5ty5c8rIyFBQUJBNe1BQkPbv35/tOklJSdn2T0pKyrZ/QkKChg0blqU9NDTUwarhLP7jXV3Bg4nj7hocd9fguLvGnTzuFy9elL+//y37uDTc3A3x8fE2Z3oyMzN1/vx5PfTQQ7JYLC6s7O64cOGCQkNDdeLECfn5+bm6nAcGx901OO6uwXF3jQftuBuGoYsXL6p48eK37evScFO0aFG5u7srOTnZpj05OVnBwcHZrhMcHGxXfy8vL3l5edm0FSpUyPGi71N+fn4PxJv/XsNxdw2Ou2tw3F3jQTrutztjc5NLJxR7enqqVq1aWrVqlbUtMzNTq1atUmRkZLbrREZG2vSXpBUrVuTYHwAAPFhcflkqLi5OsbGxql27turUqaPx48crLS1NnTt3liR17NhRISEhSkhIkCT17dtXDRs21JgxY9SiRQvNnj1b27dv15QpU1y5GwAA4B7h8nDTtm1bnT17VkOGDFFSUpKqV6+uZcuWWScNJyYmys3tfyeY6tWrp1mzZuntt9/Wm2++qYcfflhff/21Kleu7KpduKd5eXlp6NChWS7N4c7iuLsGx901OO6uwXHPmcXIzT1VAAAA9wmXf4gfAACAMxFuAACAqRBuAACAqRBuAACAqRBuAACAqRBuTGzdunWKiYlR8eLFZbFYcvxyUThPQkKC/u///k8FCxZUYGCgWrVqpV9//dXVZZnexIkTVbVqVesntUZGRmrp0qWuLuuBM2rUKFksFvXr18/VpZjaO++8I4vFYvMoX768q8u6pxBuTCwtLU3VqlXThAkTXF3KA+OHH35Qz549tWXLFq1YsULXr19X06ZNlZaW5urSTK1EiRIaNWqUduzYoe3bt6tx48Z66qmn9PPPP7u6tAfGtm3bNHnyZFWtWtXVpTwQKlWqpNOnT1sfGzZscHVJ9xSXf4gf7pxmzZqpWbNmri7jgbJs2TKb5zNmzFBgYKB27Nihxx57zEVVmV9MTIzN8/fee08TJ07Uli1bVKlSJRdV9eC4dOmSXnjhBU2dOlUjRoxwdTkPhHz58uX4nYrgzA1wR6WmpkqSihQp4uJKHhwZGRmaPXu20tLS+M65u6Rnz55q0aKFoqKiXF3KA+PgwYMqXry4SpcurRdeeEGJiYmuLumewpkb4A7JzMxUv379VL9+fb4e5C7Ys2ePIiMjdfXqVRUoUECLFi1SxYoVXV2W6c2ePVs7d+7Utm3bXF3KAyMiIkIzZszQI488otOnT2vYsGFq0KCB9u7dq4IFC7q6vHsC4Qa4Q3r27Km9e/dyLfwueeSRR7R7926lpqZq/vz5io2N1Q8//EDAuYNOnDihvn37asWKFfL29nZ1OQ+Mv043qFq1qiIiIlSqVCnNnTtXXbt2dWFl9w7CDXAH9OrVS99++63WrVunEiVKuLqcB4Knp6fKli0rSapVq5a2bdumDz74QJMnT3ZxZea1Y8cOnTlzRjVr1rS2ZWRkaN26dfr444+Vnp4ud3d3F1b4YChUqJDKlSunQ4cOubqUewbhBnAiwzDUu3dvLVq0SGvXrlV4eLirS3pgZWZmKj093dVlmFqTJk20Z88em7bOnTurfPnyeuONNwg2d8mlS5d0+PBhdejQwdWl3DMINyZ26dIlmyR/9OhR7d69W0WKFFHJkiVdWJl59ezZU7NmzdI333yjggULKikpSZLk7+8vHx8fF1dnXvHx8WrWrJlKliypixcvatasWVq7dq2WL1/u6tJMrWDBglnmk/n6+uqhhx5intkdNHDgQMXExKhUqVL67bffNHToULm7u6t9+/auLu2eQbgxse3bt6tRo0bW53FxcZKk2NhYzZgxw0VVmdvEiRMlSY8//rhN+/Tp09WpU6e7X9AD4syZM+rYsaNOnz4tf39/Va1aVcuXL9cTTzzh6tIApzt58qTat2+v33//XQEBAXr00Ue1ZcsWBQQEuLq0e4bFMAzD1UUAAAA4C59zAwAATIVwAwAATIVwAwAATIVwAwAATIVwAwAATIVwAwAATIVwAwAATIVwAwAATIVwAwAATIVwAwAATIVwAwAATOX/Aezi+dumZSLfAAAAAElFTkSuQmCC",
      "text/plain": [
       "<Figure size 640x480 with 1 Axes>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "print(\"\\nÉvaluation de l'agent\")\n",
    "test_agent(model, test_df, transmat)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
